remove reference to temp, Display on a correct line
arduino-libraries/Arduino_SensorKit pull request #7
Opened 2020-12-17 19:44 UTC by marcmerlin

I unfortunately wasted 1H trying to use the oled due to this example.
Display lines need to be 9, 18, 27, 36, 45, 54
Using 33 is not good, it's an incorrect value that ends up in the wrong place, and gives the
impression that you can give any Y coordinate, when in fact you cannot.
If you don't, text gets overlayed on top of other text, even though it shouldn't according to Y

See https://github.com/arduino-libraries/Arduino_SensorKit/pull/6 for an example.

2021-01-04 20:07 UTC, noppatoppa commented
> Display lines need to be 9, 18, 27, 36, 45, 54
> Using 33 is not good, it's an incorrect value that ends up in the wrong place, and gives the

Wait, are you sure? I might be missing something, but looks like using anything larger than (0,8) just loops the screen over. This is using the normal sized fonts from the u8x8 font list (https://github.com/olikraus/u8g2/wiki/fntlist8x8). Using larger (1x2) moves characters over others.

My example code:
`#include "Arduino_SensorKit.h"

void setup() {
  Oled.begin();
  Oled.setFlipMode(true);
}

void loop() {
  Oled.setFont(u8x8_font_chroma48medium8_r);
  for (int i = 0; i <= 8; i++) {
    Oled.setCursor(0, i);
    if (i != 8) {
      Oled.print(i);
    }
    else {
      Oled.print("... goes over");
    }
  }
  delay(1000);
}`

2021-01-04 20:48 UTC, marcmerlin commented
I noticed that with U8x8 line 33 did not print at line 33 (although it does with U8g2)
Does this print on line 33 for you with the basic example?
Try setting the cursor lines 9, 18, 27, 36, 45, 54 to see the difference

2021-01-05 07:04 UTC, noppatoppa commented
> I noticed that with U8x8 line 33 did not print at line 33 (although it does with U8g2)
> Does this print on line 33 for you with the basic example?
> Try setting the cursor lines 9, 18, 27, 36, 45, 54 to see the difference

I think u8x8 setCursor works not as pixel rows, but rows of 8x8 squares: "Arguments:  x, y: Column/row position for the cursor of the print function." (https://github.com/olikraus/u8g2/wiki/u8x8reference#setcursor). Anything printed over the row limit loops over to the top again. If you run getRows (https://github.com/olikraus/u8g2/wiki/u8x8reference#getrows) on the SensorKit OLED, you get 8 rows. So printing to row 33 is actually printed on row number 1 (range 0, 7) because (34 % 8 == 2).

So printing anything over row num 7 is futile. That's why I'd use Oled.home() to reset cursor and Oled.getRows() to get row count if you want other placements.

Try this example to see what I mean (sorry about the butt ugly formatting):
#include "Arduino_SensorKit.h"

void setup() {
  Serial.begin(9600);
  Oled.begin();
  Oled.setFlipMode(true);
}

void loop() {
  // Works with any standard size u8x8 font
  Oled.setFont(u8x8_font_chroma48medium8_r);
  Serial.println(Oled.getRows());
  // Populate rows with numbers 0 to 7
  for (int i = 0; i <= 8; i++) {
    Oled.setCursor(0, i);
    if (i < 8) {
      Oled.print(i);
    }
  }
  // Move the looped values a bit on the x axis to see result
  Oled.setCursor(3, 9); // This is line num 1
  Oled.print(9);
  Oled.setCursor(3, 18);
  Oled.print(18);
  Oled.setCursor(3, 27);
  Oled.print(27);
  Oled.setCursor(3, 36);
  Oled.print(36);
  Oled.setCursor(3, 45); // This is line num 5
  Oled.print(45);
  
  delay(1000);
}

2021-01-05 07:15 UTC, noppatoppa commented
I'm guessing U8g2 works on pixel coordinate basis and U8x8 on 8 by 8 pixel grid basis. And that's confusing this for everybody?

2021-01-05 09:17 UTC, marcmerlin commented
@noppatoppa  actually what you're saying is very possible, yes.
Either way, using line 33 does not print at line 33, which is one of the things my patch corrects.

2021-01-05 10:14 UTC, noppatoppa commented
@marcmerlin what I'm trying to say is

> Using 33 is not good, it's an incorrect value that ends up in the wrong place, and gives the
> impression that you can give any Y coordinate, when in fact you cannot.

But my point is, that you can and it produces expected results.

> Either way, using line 33 does not print at line 33, which is one of the things my patch corrects.
But it kinda does not. It now prints at line 3, though it loops over the screen several times to get there. And using line 33 prints on line 1. So both are equally wrong IMHO.

Really sorry about the potato quality of the photo, but the top right row is 33 and row number 3 is 27. But if you print on row 28 (that is, row 4) it prints correctly without overlap.
![oled_arduino](https://user-images.githubusercontent.com/36483236/103633441-65dda500-4f4e-11eb-9778-4509b1192da1.jpg)

I'm just a user, but banged my head against the same wall.

2021-01-05 10:20 UTC, noppatoppa requested changes
Suggested changes based on comments I made. Again, I'm just a user and not at all responsible for the library.

2021-01-05 10:20 UTC, noppatoppa commented on examples/Oled_Display/Oled_Display.ino
>    Oled.refreshDisplay();
Not needed with U8x8.
> Writes directly to the display. No buffer in the microcontroller required.
(https://github.com/olikraus/u8g2/wiki)

2021-01-05 10:20 UTC, noppatoppa commented on examples/Oled_Display/Oled_Display.ino
> +  Oled.setCursor(0, 27);
This could be
```suggestion
  Oled.setCursor(0, 3);

```

Or
```suggestion
  Oled.home();

```

2021-01-05 22:18 UTC, marcmerlin commented
Thanks for the info, you are correct on the cursor value, I fixed it.
I also updated https://github.com/arduino-libraries/Arduino_SensorKit/pull/6

2021-01-06 07:02 UTC, noppatoppa approved these changes
Thanks! 👌

2021-01-12 17:20 UTC, merged

2021-01-12 17:20 UTC, marqdevx commented
@noppatoppa @marcmerlin 
Thanks!